language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2.3
  - ruby-head
  - rbx

branches:
  only:
    - master

gemfile:
  - Gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx

script: bundle exec rake test
